name: The Events Calendar Testing

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (4 times per day)
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: Test TEC (WP ${{ matrix.wordpress }}, PHP ${{ matrix.php }})
    strategy:
      fail-fast: false
      matrix:
        wordpress: ['6.7', '6.8']
        php: ['8.1', '8.2']
    
    uses: stellarwp/testflow/.github/workflows/testflow.yml@main
    with:
      config: 'testflow.yaml'
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
      plugin-zips: 'the-events-calendar'
      test-patterns: 'tests/e2e/**/*.test.ts'
      workers: '1'
      retries: '2'
      timeout: '30000'
      debug: ${{ inputs.debug || false }}
      cache-key: 'tec-${{ matrix.wordpress }}-${{ matrix.php }}' 