name: The Events Calendar Testing

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (4 times per day)
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

jobs:
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Install Playwright browsers
        run: bunx playwright install --with-deps chromium
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            .testflow-cache
          key: testflow-${{ runner.os }}-${{ hashFiles('**/bun.lockb', '**/package.json') }}-${{ github.sha }}

  test:
    name: Test TEC (WP ${{ matrix.wordpress }}, PHP ${{ matrix.php }})
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        wordpress: ['6.7', '6.8']
        php: ['8.1', '8.2']
    
    uses: stellarwp/testflow/.github/workflows/testflow.yml@main
    with:
      config: 'testflow.yaml'
      install-browsers: false
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
      plugin-zips: 'the-events-calendar'
      test-patterns: 'tests/e2e/**/*.test.ts'
      workers: '1'
      retries: '2'
      timeout: '30000'
      debug: ${{ inputs.debug || false }}
      cache-key: 'tec-${{ matrix.wordpress }}-${{ matrix.php }}' 